config:
  send_anonymous_usage_stats: False

default:
  outputs:

    dev: # User-Password config
      type: snowflake
      account: mw85066
      user: DBT_CLOUD_DEV
      password: Kachabh@88
      role: EDW_DBT_SERVICE_ETL_ROLE_DEV
      database: DEV
      warehouse: EDW_DBT_DEV_WH
      schema: ANALYTICS
      threads: 2
      client_session_keep_alive: False

  target: dev
